version: "3.9"
services:
  postgr:
    build: ./postgr
    environment:
      POSTGRES_DB: "chain"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "123"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    expose:
      - "5432"
    ports:
      - "5432:5432"
  app:
    build: ./app
    depends_on:
      - postgr
    expose:
      - "5000"
    ports:
      - "5000:5000"
