version: "3.9"
services:
  postgr:
    restart: always
    build: ./postgr
    command: flask run
    environment:
      POSTGRES_DB: "chain"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "123"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - /home/ajioxa/prove/postgr:/var/lib/postgresql/data
    ports:
      - "8001:5432"
    networks:
      back:
        ipv4_address: 172.16.238.4
      default:
  app:
    depends_on:
      - postgr
    restart: always
    build: ./app
  #  container_name: applyc
    ports:
      - "8000:5000"
    networks:
      back:
        ipv4_address: 172.16.238.5
      default:
networks:
  back:
    driver: bridge
    internal: true
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/16
  default:
    driver: bridge
