version: "3.9"
services:
  postgr:
    restart: always
    build: ./postgr
    container_name: postgr14
    environment:
      POSTGRES_DB: "chain"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "123"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - /home/ajioxa/prove/postgr:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - default
  app:
    depends_on:
      - postgr
    restart: always
    build: ./app
    container_name: applyc
    links:
      - postgr:db

    ports:
      - "5000:5000"
    networks:
      - default
networks:
  default:
