version: "3.9"
services:
  postgres:
    build:
      context: ./postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=chain
      - POSTGRES_PASSWORD=123
  app:
    build: ./app
    ports:
      - "80:5000"
    depends_on:
      - postgres
    environment:
      WAIT_HOSTS: postgres:5432
    env_file:
      - ./.env.dev